ENV['DEVICE'] = 'iPhone 11' unless ENV.has_key?('DEVICE')
ENV['IOS_VERSION'] = '13.0' unless ENV.has_key?('IOS_VERSION')

lane :build do
    analyze_scheme("SalesforceReactTestApp")
end

lane :test do
    test_scheme("SalesforceReactTestApp")
end

def test_scheme(scheme)
  scan(
      workspace: '../ios/SalesforceReactTests/SalesforceReactTestApp.xcworkspace',
      scheme: scheme,
      device: ENV['DEVICE'] + ' (' + ENV['IOS_VERSION'] + ')',
      output_directory: 'test_output',
      output_types: 'html,junit',
      code_coverage: true,
      skip_build: true
  )
end

def analyze_scheme(scheme)
    xcodebuild(
        xcargs: 'CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES',
        workspace: '../ios/SalesforceReactTests/SalesforceReactTestApp.xcworkspace',
        scheme: scheme,
        sdk: 'iphonesimulator',
    )
end
