# Validate changes to this class with: curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  branch: dev

coverage:
  precision: 2
  round: down
  range: "60...80"

  status:
    # Overall Libarary Requirements
    project:
      default: true
      SalesforceReactSDK:
        threshold: 0%
        paths:
          - "ios/"

comment:
  layout: "reach, diff"
  behavior: default
  require_changes: false