require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '14.0'

use_frameworks!

project 'SalesforceReactTestApp.xcodeproj'
target 'SalesforceReactTestApp' do
end

target 'SalesforceReactTests' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'React-RCTTest', :path => '../RCTTest'
  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')
  pod 'SalesforceReact', :path => '../..'
end

post_install do |installer|
  react_native_post_install(installer)

  # Cocoapods workaround for M1 machines
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
  # Keeping Mobile SDK iOS deployment target at 14 (__apply_Xcode_12_5_M1_post_install_workaround changes it to 11)
  installer.pods_project.targets.each do |target|
    if ['SalesforceAnalytics', 'SalesforceSDKCommon', 'SalesforceSDKCore', 'SmartStore', 'MobileSync', 'SalesforceReact'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
