require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'


platform :ios, '16.0'
prepare_react_native_project!

project 'SalesforceReactTestApp.xcodeproj'
target 'SalesforceReactTestApp' do
end

target 'SalesforceReactTests' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'React-RCTTest', :path => '../RCTTest'
  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')
  pod 'SalesforceReact', :path => '../node_modules/react-native-force'

  pre_install do |installer|
    # Mobile SDK pre install
    mobile_sdk_pre_install(installer)  
  end


  post_install do |installer|
    # React native post install
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )  
    
    # Mobile SDK post install
    mobile_sdk_post_install(installer)
  end
end
